baseURL = "https://blog.minkedup.xyz"
languageCode = "en-us"
title = "Mickey's Blog"
enableEmoji = true

disableKinds = ["rss", "sitemap", "taxonomy", "term"]

[sitemap]
  disable = true

[minify]
  minifyOutput = true


[frontmatter]
date = [":filename"]

[permalinks]
blog = "/blog/:year/:month/:day/:slug/"
